
group.id=01
group.name=Grupo POO
project.version=1.0

board.size=10
board.columns.start=A
board.columns.end=J
fleet.sizes=5,4,3,3,2
fleet.names=PortaAvioes,Encouracado,Cruzador,Submarino,Destroyer

db.enabled=true
db.type=sqlite
db.sqlite.file=batalha.db
db.auto_migrate=true

ui.show_legend=true
ui.show_own_ships=true

game.mode=PLAY
game.seed=42
